### ISSUE TITLE
can't find the file:  Pandora/InstallPandora.py 

### ISSUE THREAD

**Issue by shiqinfeng1** [RichardFrangenberg/Pandora#4]
Pandora_Setup.bat requires the python file Pandora/InstallPandora.py , but I cannot find it anywhere.

**Comment by RichardFrangenberg** [comment]
That sounds like that you are using a very old version. Just upgrade to the latest one and that should be fixed.

**Comment by shiqinfeng1** [comment]
Sorry，I don't quite understand what you mean.
        I used the latest development branch.  In Pandora folder, it includes  :
            Plugins 	multilayer exr improvements 	16 days ago
	    Scripts 	v1.0.3.7 	2 days ago
	    Setup_Integrations.bat 	plugin structure 	8 months ago
	    Setup_Startmenu.bat 	plugin structure 	8 months ago
	    Uninstall.bat 	plugin structure 	8 months ago
    Could you explain again？ Thanks！

**Comment by RichardFrangenberg** [comment]
Sorry, you were right, this happened also in the current version. I just fixed it. If you use the latest development branch then it should work fine now.
