### ISSUE TITLE
can't run PandoraCoordinator in mac

### ISSUE THREAD

**Issue by shiqinfeng1** [RichardFrangenberg/Pandora#8]
Since there is no environment variable userprofile on mac, It unable to generate pandoraConfig path. So when initializing PandoraCoordinator， should first determine the current operating system：

```
if platform.system() == "Windows":
	pandoraConfig = os.path.join(os.environ["userprofile"], "Documents", "Pandora", "Pandora.json")
else:
	pandoraConfig = ""
```

**Comment by RichardFrangenberg** [comment]
Pandora does not support Mac at the moment. It's compatible with Windows and the Pandora Coordinator can also run on a linux server. I never tested it on Mac, but I guess a lot of modifications would be necessary to support that. At the moment I'm not working on the Mac support.

**Comment by shiqinfeng1** [comment]
OK. I just run it  on mac, and no problem with renderSlaves/renderHandler( running on win10) communication. The status of the slave is also displayed. Now I have migrated to win10.
